[package]
name = "rootblocks"
version = "0.1.0"
authors = ["YohananDiamond <mitonanan12@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
bindgen = "0.53.1"
cc = "1.0"

[dependencies]
